apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qern
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qern
    app.kubernetes.io/part-of: byoc-app-spbq
  name: qern
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: qern
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: qern
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-gzls-tenant/byoc-app-spbq/qern@sha256:9174e526348a9d61cd67a03760ef04d3e0f120313a3f1387c7b3c2c13d9acf44
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
