apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: qern
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-gzls-tenant/byoc-app-spbq/qern@sha256:9174e526348a9d61cd67a03760ef04d3e0f120313a3f1387c7b3c2c13d9acf44
        name: my-java-quarkus
        resources: {}
status: {}
